encoding: utf-8

# http://renyuanz.github.io/leonids/theme-setup/

# Site settings
title: Juan Ignacio Sánchez Lara, Software Engineer
email: juanignaciosl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Juan Ignacio Sánchez Lara code-related stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://juanignaciosl.github.io" # the base hostname & protocol for your site
twitter_username: juanignaciosl
github_username:  juanignaciosl

# Build settings
markdown: kramdown

exclude: [.idea]

owner:
  name: Juan Ignacio Sánchez Lara
  avatar: avatar-4.jpg
  job: "Software Engineer"
  bio: "[Passionate Software Engineer](https://www.linkedin.com/in/juanignaciosl/) ([resumé](misc/cv.pdf)). <br />Remoting from Valladolid, Spain. <br />Interests: Engineering Management, PostgreSQL, Agile, Scala, Python, geo...<br /><br />I'm also an [amateur writer, behind Ignacio C. Sierra](http://ignaciocsierra.com/) pseudonym."
  email: juanignaciosl@gmail.com
  blog: http://www.juanignaciosl.com
  # medium: juanignaciosl
  disqus-shortname: juanignaciosl-github-io
  twitter: juanignaciosl #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-58621694-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: juanignaciosl #username
  stackoverflow: 351721/juanignaciosl #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: juanignaciosl #username
  xing: #username
  instagram: juanignaciosl #username
  lastfm: juanignaciosl #username
  spotify: juanignaciosl #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: juanignaciosl #username
  codepen: #username
